/**
 * Created by rosemariegonzales on 8/2/16.
 */

var mainTextDivBottom;
var option1OuterLabelDiv, option2OuterLabelDiv, option1InnerLabelDiv, option2InnerLabelDiv;
var googleMap;//variable used to create Google Maps object
var googleService;//variable used to create new Google Service object
var losAngeles = {lat: 34.0522, lng: -118.2437};//sets the lattitude and longtitude for Los Angeles
var place;//stores the randomly picked object from results generated by the googleTextSearch function
var placeName;
var placeNameDiv;
var placeImageURL;
var placeImage;
var placeDiv;
var songArray = [];
var typeOfSong= "aint too proud";

//Initialize Google Map and sets the location to the city of Los Angeles
function initializeMap() {
    googleMap = new google.maps.Map(document.getElementById('map'), {
        center: losAngeles,
        zoom: 17
    });
}

//Google Text Search Function - based on a string search
function googleTextSearch(googleQueryValue){
    googleService = new google.maps.places.PlacesService(googleMap);
    googleService.textSearch({
        location: losAngeles,
        radius: 1000,
        query: googleQueryValue
    }, processResults);

}

//Function to call in order to process results from the googleTextSearch function
//Images and html elements displayed as player's options/choices are dynamically created from this function
function processResults(results, status) {
    if (status !== google.maps.places.PlacesServiceStatus.OK) {
        return;
    } else {
        //Randomly pick a place from the results based on player's choice
        var resultsIndex = Math.floor(Math.random() * results.length);
        place = results[resultsIndex];
        placeName = place.name;
        placeNameDiv = $('<div>').addClass('innerTextDiv innerTextDivSmall col-xs-10');
        placeNameDiv.append("<p>").text(placeName);
        placeImageURL = place.photos[0].getUrl({'maxWidth': 500, 'maxHeight': 500});
        placeImage = $('<img>').attr('src', placeImageURL);
        placeDiv = $('<div>').addClass('optionDiv col-xs-4');
        placeDiv.append(placeImage, placeNameDiv);
        $('.mainContent').append(placeDiv);
        console.log('results array: ', results);
        console.log('results array length: ', results.length);
        console.log('random place: ', place.name);
        console.log(placeName, placeImageURL);
    }
}

//Adds Google Logo to the page as required by Google when using Google API
function poweredByGoogle(){
    var googleLogoDiv = $('<div>');
    var googleLogo = $('<img>').attr('src','images/powered_by_google_on_white.png');
    googleLogoDiv.append(googleLogo);
    $('body').append(googleLogoDiv);
}
function playPause() {
    var audio = document.getElementById("audio");
    if (audio.paused) {
        audio.play();
        $('#playIcon').removeClass();
        $('#playIcon').addClass('glyphicon glyphicon-pause');

    } else {
        audio.pause();
        $('#playIcon').removeClass();
        $('#playIcon').addClass('glyphicon glyphicon-play');
    }
}

function listenAjax() {
    //calls query with music as only criteria first

    $.ajax({
        url: 'https://api.spotify.com/v1/search',
        data: {
            q: typeOfSong,
            type: 'track'
        },

        success: function (response) {
            console.log('spotify', response);

            for (i = 0; i < response.tracks.items.length; i++) {

                var tracks = response.tracks.items[i];

                var song = {
                    audio: tracks.preview_url
                };
                songArray.push(song);
                console.log(songArray[0]);
            }
            $('#audio').attr('src', songArray[0].audio);
            playPause();
        }

    });
}
function clearMainContent(){
    $('.mainContent > *').remove();
}
function buildTemplate(){
    mainTextDivBottom = $('<div>').addClass('outerTextDiv outerTextDivLarge col-xs-12');
    mainTextDivTop = $('<div>').addClass('innerTextDiv innerTextDivLarge col-xs-11');
    $(mainTextDivBottom).append(mainTextDivTop);
    option1OuterLabelDiv = $('<div>').addClass('outerLabelDiv col-xs-4');
    option1InnerLabelDiv = $('<div>').addClass('innerLabelDiv col-xs-10');
    option1OuterLabelDiv.append(option1InnerLabelDiv);
    option2OuterLabelDiv = $('<div>').addClass('outerLabelDiv col-xs-4');
    option2InnerLabelDiv = $('<div>').addClass('innerLabelDiv col-xs-10');
    option2OuterLabelDiv.append(option2InnerLabelDiv);


    $('.mainContent').append(mainTextDivBottom, option1OuterLabelDiv,option2OuterLabelDiv);
}
function breakfastTime(){
    var breakfastQuestion = $('<h2>').text('You wake up to the light of California sunshine pouring through your hotel window. You’re hungry. Breakfast?').addClass('question');
    var breakfastOption1 = 'Pancakes';
    var breakfastOption2 =  'Eggs';
    var breakfastOption1ChosenText = 'It’s LA, you figure, so you go with the Huevos Rancheros. They’re good. You think they’re better than they are at home, but you wonder if you’re just telling yourself that.';
    var breakfastOption2ChosenText = 'Pancakes, yes! Not very LA, maybe, and sure, there are a hundred places back home with pancakes at least as good, but they’re comforting all the same. You feel like you’ve got your bearings in California now. You’re ready for the day.';
    $(mainTextDivTop).append(breakfastQuestion);
    $(option1InnerLabelDiv).text(breakfastOption1);
    $(option2InnerLabelDiv).text(breakfastOption2);
    googleTextSearch('pancakes');
    googleTextSearch('breakfast eggs');
}
$(document).ready(function(){
    listenAjax();
    $('#playButton').click(playPause);
    $('.startButton').click(function(){
        clearMainContent();
        buildTemplate();
        breakfastTime();
    });
    initializeMap();
    poweredByGoogle();
});
