/**
 * Created by rosemariegonzales on 8/2/16.
 */

var googleMap;//variable used to create Google Maps object
var googleService;//variable used to create new Google Service object
var losAngeles = {lat: 34.0522, lng: -118.2437};//sets the lattitude and longtitude for Los Angeles
var place;//stores the randomly picked object from results generated by the googleTextSearch function
var songArray = [];
var typeOfSong= "aint too proud";

//Initialize Google Map and sets the location to the city of Los Angeles
function initializeMap() {
    googleMap = new google.maps.Map(document.getElementById('map'), {
        center: losAngeles,
        zoom: 17
    });
}

//Google Text Search Function - based on a string search
function googleTextSearch(googleQueryValue){
    googleService = new google.maps.places.PlacesService(googleMap);
    googleService.textSearch({
        location: losAngeles,
        radius: 1000,
        query: googleQueryValue
    }, processResults);
}

//Function to call in order to process results from the googleTextSearch function
//Images and html elements displayed as player's options/choices are dynamically created from this function
function processResults(results, status) {
    if (status !== google.maps.places.PlacesServiceStatus.OK) {
        return;
    } else {
        //Randomly pick a place from the results based on player's choice
        var resultsIndex = Math.floor(Math.random() * results.length);
        place = results[resultsIndex];
        var placeName = $('<p>').text(place.name);
        var placeImageURL = place.photos[0].getUrl({'maxWidth': 500, 'maxHeight': 500});
        var placeImage = $('<img>').attr('src', placeImageURL);
        var placeContainer = $('<div>');
        placeContainer.append(placeImage, placeName);
        $('body').append(placeContainer);
        console.log('results array: ', results);
        console.log('results array length: ', results.length);
        console.log('resultsIndex: ', resultsIndex);
        console.log('random place: ', place.name);
        console.log(placeImageURL);
    }
}

//Adds Google Logo to the page as required by Google when using Google API
function poweredByGoogle(){
    var googleLogoDiv = $('<div>');
    var googleLogo = $('<img>').attr('src','images/powered_by_google_on_white.png');
    googleLogoDiv.append(googleLogo);
    $('body').append(googleLogoDiv);
}
function playPause() {
    var audio = document.getElementById("audio");
    if (audio.paused) {
        audio.play();
        $('#playIcon').removeClass();
        $('#playIcon').addClass('glyphicon glyphicon-pause');

    } else {
        audio.pause();
        $('#playIcon').removeClass();
        $('#playIcon').addClass('glyphicon glyphicon-play');
    }
}

function listenAjax() {
    //calls query with music as only criteria first

    $.ajax({
        url: 'https://api.spotify.com/v1/search',
        data: {
            q: typeOfSong,
            type: 'track'
        },

        success: function (response) {
            console.log('spotify', response);

            for (i = 0; i < response.tracks.items.length; i++) {

                var tracks = response.tracks.items[i];

                var song = {
                    audio: tracks.preview_url
                };
                songArray.push(song);
                console.log(songArray[0]);
            }
            $('#audio').attr('src', songArray[0].audio);
            playPause();
        }

    });
}
function clearMainContent(){
    $('.mainContent > *').remove();
}
$(document).ready(function(){
    listenAjax();
    $('#playButton').click(playPause);
    $('.startButton').click(clearMainContent);
    initializeMap();
    poweredByGoogle();
});
